# Generated by Django 4.1.4 on 2022-12-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
