# Generated by Django 4.1.4 on 2022-12-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_project', '0002_song_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='release_date',
            new_name='album_release_date',
        ),
    ]
